/**
 * Raw Hono application setup.
 * This file contains all routes and middleware without the Sentry wrapper.
 * Used by both production (index.ts) and tests (testWorker.ts).
 */
import { ApiException, fromHono } from "chanfana";
import { Hono } from "hono";
import { ContentfulStatusCode } from "hono/utils/http-status";
import { DummyEndpoint } from "./endpoints/dummyEndpoint";
import pkg from "../package.json";
import { getOpenApiInfo, getScalarHtml, type AppMeta } from "./app-meta";
import { registerBetterAuthRoutes } from "./auth/routes";
import { createCorsMiddleware } from "./middleware/cors";
import type { Bindings } from "./types/bindings";
import {
	AuthSignUpEndpoint,
	AuthSignInEndpoint,
	AuthSignOutEndpoint,
	AuthSessionEndpoint,
	AuthJwksEndpoint,
	AuthForgotPasswordEndpoint,
	AuthResetPasswordEndpoint,
} from "./endpoints/auth/openapi";
import {
	GetUserSettingsEndpoint,
	UpdateUserSettingsEndpoint,
	GetOrganizationSettingsEndpoint,
	UpdateOrganizationSettingsEndpoint,
	GetResolvedSettingsEndpoint,
	GetOrganizationMembershipEndpoint,
} from "./endpoints/settings/openapi";
import {
	ListAuditLogsEndpoint,
	GetAuditLogEndpoint,
	VerifyAuditChainEndpoint,
	ExportAuditLogsEndpoint,
} from "./endpoints/audit/openapi";
import {
	GetSubscriptionStatusEndpoint,
	GetSubscriptionPlansEndpoint,
	CreateCheckoutSessionEndpoint,
	ChangeSubscriptionPlanEndpoint,
	CancelSubscriptionEndpoint,
	ReactivateSubscriptionEndpoint,
	GetSubscriptionInvoicesEndpoint,
	GetCustomerPortalEndpoint,
	GetSubscriptionUsageEndpoint,
} from "./endpoints/subscription/openapi";
import {
	ListLicensesEndpoint,
	GenerateLicenseEndpoint,
	GetLicenseEndpoint,
	RevokeLicenseEndpoint,
	RenewLicenseEndpoint,
	ActivateLicenseEndpoint,
	VerifyLicenseEndpoint,
	GetCurrentLicenseEndpoint,
} from "./endpoints/license/openapi";
import {
	GetAmlComplianceSettingsEndpoint,
	PutAmlComplianceSettingsEndpoint,
	PatchAmlComplianceSettingsEndpoint,
} from "./endpoints/aml-settings/openapi";
import { settingsRoutes } from "./routes/settings";
import { internalSettingsRoutes } from "./routes/internal-settings";
import { amlSettingsProxyRoutes } from "./routes/aml-settings-proxy";
import { auditRoutes } from "./routes/audit";
import { internalAuditRoutes } from "./routes/internal-audit";
import { subscriptionRoutes } from "./routes/subscription";
import { licenseRoutes } from "./routes/license";
import { webhookRoutes } from "./routes/webhooks";
import { internalSubscriptionRoutes } from "./routes/internal-subscription";

// Start a Hono app
export const app = new Hono<{ Bindings: Bindings }>();

const appMeta: AppMeta = {
	name: pkg.name,
	version: pkg.version,
	description: pkg.description,
};

// Global middleware - Better Auth handles its own CORS via trustedOrigins config
// Only apply CORS middleware to non-Better Auth routes
const corsMiddleware = createCorsMiddleware();
app.use("*", async (c, next) => {
	if (c.req.path.startsWith("/api/auth")) {
		return next();
	}
	return corsMiddleware(c, next);
});

app.onError((err, c) => {
	if (err instanceof ApiException) {
		// If it's a Chanfana ApiException, let Chanfana handle the response
		return c.json(
			{ success: false, errors: err.buildResponse() },
			err.status as ContentfulStatusCode,
		);
	}

	console.error("Global error handler caught:", err); // Log the error if it's not known

	// For other errors, return a generic 500 response
	return c.json(
		{
			success: false,
			errors: [{ code: 7000, message: "Internal Server Error" }],
		},
		500,
	);
});

// Setup OpenAPI registry
const openapi = fromHono(app, {
	// Keep the autogenerated docs available; serve Scalar at `/docsz`.
	docs_url: "/docs",
	schema: {
		info: getOpenApiInfo(appMeta),
	},
});

app.get("/", (c) => {
	if (c.req.header("x-force-error") === "1") {
		throw new Error("Forced error");
	}

	return c.json({ name: appMeta.name, version: appMeta.version });
});

app.get("/healthz", (c) => {
	return c.json({ ok: true });
});

app.get("/docsz", (c) => {
	return c.html(getScalarHtml(appMeta));
});

// Register Better Auth routes (actual implementation - handles requests)
// Must be registered BEFORE OpenAPI documentation routes so they handle requests first
registerBetterAuthRoutes(app);

// Register Better Auth OpenAPI documentation (for API docs generation only)
// These routes are registered after Better Auth routes, so they won't intercept requests
openapi.post("/api/auth/sign-up", AuthSignUpEndpoint);
openapi.post("/api/auth/sign-in", AuthSignInEndpoint);
openapi.post("/api/auth/sign-out", AuthSignOutEndpoint);
openapi.get("/api/auth/session", AuthSessionEndpoint);
openapi.get("/api/auth/jwks", AuthJwksEndpoint);
openapi.post("/api/auth/forgot-password", AuthForgotPasswordEndpoint);
openapi.post("/api/auth/reset-password", AuthResetPasswordEndpoint);

// Register Settings routes (actual implementation)
app.route("/api/settings", settingsRoutes);

// Register AML Compliance Settings proxy routes (proxies to aml-svc via service binding)
app.route("/api/settings/aml-compliance", amlSettingsProxyRoutes);

// Register AML Settings OpenAPI documentation
openapi.get(
	"/api/settings/aml-compliance/:orgId",
	GetAmlComplianceSettingsEndpoint,
);
openapi.put(
	"/api/settings/aml-compliance/:orgId",
	PutAmlComplianceSettingsEndpoint,
);
openapi.patch(
	"/api/settings/aml-compliance/:orgId",
	PatchAmlComplianceSettingsEndpoint,
);

// Register Internal routes for service bindings
app.route("/internal/settings", internalSettingsRoutes);

// Register Settings OpenAPI documentation
openapi.get("/api/settings/user", GetUserSettingsEndpoint);
openapi.patch("/api/settings/user", UpdateUserSettingsEndpoint);
openapi.get(
	"/api/settings/organization/:orgId",
	GetOrganizationSettingsEndpoint,
);
openapi.patch(
	"/api/settings/organization/:orgId",
	UpdateOrganizationSettingsEndpoint,
);
openapi.get(
	"/api/settings/organization/:orgId/membership",
	GetOrganizationMembershipEndpoint,
);
openapi.get("/api/settings/resolved", GetResolvedSettingsEndpoint);

// Register Audit routes (actual implementation)
app.route("/api/audit", auditRoutes);

// Register Internal Audit routes for service bindings
app.route("/internal/audit", internalAuditRoutes);

// Register Audit OpenAPI documentation
openapi.get("/api/audit", ListAuditLogsEndpoint);
openapi.get("/api/audit/verify", VerifyAuditChainEndpoint);
openapi.get("/api/audit/:id", GetAuditLogEndpoint);
openapi.post("/api/audit/export", ExportAuditLogsEndpoint);

// Register Subscription routes (billing management)
app.route("/api/subscription", subscriptionRoutes);

// Register Subscription OpenAPI documentation
openapi.get("/api/subscription", GetSubscriptionStatusEndpoint);
openapi.get("/api/subscription/plans", GetSubscriptionPlansEndpoint);
openapi.post("/api/subscription/checkout", CreateCheckoutSessionEndpoint);
openapi.post("/api/subscription/change", ChangeSubscriptionPlanEndpoint);
openapi.post("/api/subscription/cancel", CancelSubscriptionEndpoint);
openapi.post("/api/subscription/reactivate", ReactivateSubscriptionEndpoint);
openapi.get("/api/subscription/invoices", GetSubscriptionInvoicesEndpoint);
openapi.post("/api/subscription/portal", GetCustomerPortalEndpoint);
openapi.get("/api/subscription/usage", GetSubscriptionUsageEndpoint);

// Register License routes (enterprise license management)
app.route("/api/licenses", licenseRoutes);

// Register License OpenAPI documentation
openapi.get("/api/licenses", ListLicensesEndpoint);
openapi.post("/api/licenses/generate", GenerateLicenseEndpoint);
openapi.get("/api/licenses/:id", GetLicenseEndpoint);
openapi.post("/api/licenses/:id/revoke", RevokeLicenseEndpoint);
openapi.post("/api/licenses/:id/renew", RenewLicenseEndpoint);
openapi.post("/api/licenses/activate", ActivateLicenseEndpoint);
openapi.post("/api/licenses/verify", VerifyLicenseEndpoint);
openapi.get("/api/licenses/current", GetCurrentLicenseEndpoint);

// Register Stripe Webhooks
app.route("/webhooks", webhookRoutes);

// Register Internal Subscription routes for service bindings
app.route("/internal/subscription", internalSubscriptionRoutes);

// Register other endpoints
openapi.post("/dummy/:slug", DummyEndpoint);
