/**
 * Raw Hono application setup.
 * This file contains all routes and middleware without the Sentry wrapper.
 * Used by both production (index.ts) and tests (testWorker.ts).
 */
import { ApiException, fromHono } from "chanfana";
import { Hono } from "hono";
import { ContentfulStatusCode } from "hono/utils/http-status";
import { DummyEndpoint } from "./endpoints/dummyEndpoint";
import pkg from "../package.json";
import { getOpenApiInfo, getScalarHtml, type AppMeta } from "./app-meta";
import { registerBetterAuthRoutes } from "./auth/routes";
import { createCorsMiddleware } from "./middleware/cors";
import type { Bindings } from "./types/bindings";
import {
	AuthSignUpEndpoint,
	AuthSignInEndpoint,
	AuthSignOutEndpoint,
	AuthSessionEndpoint,
	AuthJwksEndpoint,
	AuthForgotPasswordEndpoint,
	AuthResetPasswordEndpoint,
} from "./endpoints/auth/openapi";
import {
	GetUserSettingsEndpoint,
	UpdateUserSettingsEndpoint,
	GetOrganizationSettingsEndpoint,
	UpdateOrganizationSettingsEndpoint,
	GetResolvedSettingsEndpoint,
	GetOrganizationMembershipEndpoint,
} from "./endpoints/settings/openapi";
import {
	ListAuditLogsEndpoint,
	GetAuditLogEndpoint,
	VerifyAuditChainEndpoint,
	ExportAuditLogsEndpoint,
} from "./endpoints/audit/openapi";
// Note: Subscription management is now handled by Better Auth Stripe plugin
// Our custom routes only handle usage tracking and org limit checks
import {
	GetAmlComplianceSettingsEndpoint,
	PutAmlComplianceSettingsEndpoint,
	PatchAmlComplianceSettingsEndpoint,
} from "./endpoints/aml-settings/openapi";
import {
	PrepareAvatarUploadEndpoint,
	UploadAvatarEndpoint,
	DeleteAvatarEndpoint,
} from "./endpoints/upload/openapi";
import { settingsRoutes } from "./routes/settings";
import { internalSettingsRoutes } from "./routes/internal-settings";
import { amlSettingsProxyRoutes } from "./routes/aml-settings-proxy";
import { auditRoutes } from "./routes/audit";
import { internalAuditRoutes } from "./routes/internal-audit";
import { subscriptionRoutes } from "./routes/subscription";
import { organizationRoutes } from "./routes/organization";
import { webhookRoutes } from "./routes/webhooks";
import { uploadRoutes } from "./routes/upload";
import { adminRoutes } from "./routes/admin";

// Start a Hono app
export const app = new Hono<{ Bindings: Bindings }>();

const appMeta: AppMeta = {
	name: pkg.name,
	version: pkg.version,
	description: pkg.description,
};

// Global middleware - Better Auth handles its own CORS via trustedOrigins config
// Only apply CORS middleware to non-Better Auth routes
const corsMiddleware = createCorsMiddleware();
app.use("*", async (c, next) => {
	if (c.req.path.startsWith("/api/auth")) {
		return next();
	}
	return corsMiddleware(c, next);
});

app.onError((err, c) => {
	if (err instanceof ApiException) {
		// If it's a Chanfana ApiException, let Chanfana handle the response
		return c.json(
			{ success: false, errors: err.buildResponse() },
			err.status as ContentfulStatusCode,
		);
	}

	console.error("Global error handler caught:", err); // Log the error if it's not known

	// For other errors, return a generic 500 response
	return c.json(
		{
			success: false,
			errors: [{ code: 7000, message: "Internal Server Error" }],
		},
		500,
	);
});

// Setup OpenAPI registry
const openapi = fromHono(app, {
	// Keep the autogenerated docs available; serve Scalar at `/docsz`.
	docs_url: "/docs",
	schema: {
		info: getOpenApiInfo(appMeta),
	},
});

app.get("/", (c) => {
	if (c.req.header("x-force-error") === "1") {
		throw new Error("Forced error");
	}

	return c.json({ name: appMeta.name, version: appMeta.version });
});

app.get("/healthz", (c) => {
	return c.json({ ok: true });
});

app.get("/docsz", (c) => {
	return c.html(getScalarHtml(appMeta));
});

// Register Better Auth routes (actual implementation - handles requests)
// Must be registered BEFORE OpenAPI documentation routes so they handle requests first
registerBetterAuthRoutes(app);

// Register Better Auth OpenAPI documentation (for API docs generation only)
// These routes are registered after Better Auth routes, so they won't intercept requests
openapi.post("/api/auth/sign-up", AuthSignUpEndpoint);
openapi.post("/api/auth/sign-in", AuthSignInEndpoint);
openapi.post("/api/auth/sign-out", AuthSignOutEndpoint);
openapi.get("/api/auth/session", AuthSessionEndpoint);
openapi.get("/api/auth/jwks", AuthJwksEndpoint);
openapi.post("/api/auth/forgot-password", AuthForgotPasswordEndpoint);
openapi.post("/api/auth/reset-password", AuthResetPasswordEndpoint);

// Register Settings routes (actual implementation)
app.route("/api/settings", settingsRoutes);

// Register AML Compliance Settings proxy routes (proxies to aml-svc via service binding)
app.route("/api/settings/aml-compliance", amlSettingsProxyRoutes);

// Register AML Settings OpenAPI documentation
openapi.get(
	"/api/settings/aml-compliance/:orgId",
	GetAmlComplianceSettingsEndpoint,
);
openapi.put(
	"/api/settings/aml-compliance/:orgId",
	PutAmlComplianceSettingsEndpoint,
);
openapi.patch(
	"/api/settings/aml-compliance/:orgId",
	PatchAmlComplianceSettingsEndpoint,
);

// Register Internal routes for service bindings
app.route("/internal/settings", internalSettingsRoutes);

// Register Settings OpenAPI documentation
openapi.get("/api/settings/user", GetUserSettingsEndpoint);
openapi.patch("/api/settings/user", UpdateUserSettingsEndpoint);
openapi.get(
	"/api/settings/organization/:orgId",
	GetOrganizationSettingsEndpoint,
);
openapi.patch(
	"/api/settings/organization/:orgId",
	UpdateOrganizationSettingsEndpoint,
);
openapi.get(
	"/api/settings/organization/:orgId/membership",
	GetOrganizationMembershipEndpoint,
);
openapi.get("/api/settings/resolved", GetResolvedSettingsEndpoint);

// Register Audit routes (actual implementation)
app.route("/api/audit", auditRoutes);

// Register Internal Audit routes for service bindings
app.route("/internal/audit", internalAuditRoutes);

// Register Audit OpenAPI documentation
openapi.get("/api/audit", ListAuditLogsEndpoint);
openapi.get("/api/audit/verify", VerifyAuditChainEndpoint);
openapi.get("/api/audit/:id", GetAuditLogEndpoint);
openapi.post("/api/audit/export", ExportAuditLogsEndpoint);

// Register Subscription routes (usage tracking and org limits)
// Note: Checkout, cancel, upgrade are handled by Better Auth at /api/auth/subscription/*
app.route("/api/subscription", subscriptionRoutes);

// Register Organization routes (invitation lookup by ID)
app.route("/api/organization", organizationRoutes);

// Register Stripe Webhooks (card fingerprint check and usage reset)
app.route("/webhooks", webhookRoutes);

// Register Upload routes (avatar uploads via R2)
app.route("/api/upload", uploadRoutes);

// Register Upload OpenAPI documentation
openapi.post("/api/upload/avatar/prepare", PrepareAvatarUploadEndpoint);
openapi.post("/api/upload/avatar", UploadAvatarEndpoint);
openapi.delete("/api/upload/avatar/:key", DeleteAvatarEndpoint);

// Register Admin routes (KV management, etc.)
app.route("/api/admin", adminRoutes);

// Register other endpoints
openapi.post("/dummy/:slug", DummyEndpoint);
