/**
 * Raw Hono application setup.
 * This file contains all routes and middleware without the Sentry wrapper.
 * Used by both production (index.ts) and tests (testWorker.ts).
 */
import * as Sentry from "@sentry/cloudflare";
import { ApiException, fromHono } from "chanfana";
import { Hono } from "hono";
import { ContentfulStatusCode } from "hono/utils/http-status";
import { DummyEndpoint } from "./endpoints/dummyEndpoint";
import pkg from "../package.json";
import { getOpenApiInfo, getScalarHtml, type AppMeta } from "./app-meta";
import { registerBetterAuthRoutes } from "./auth/routes";
import { createCorsMiddleware } from "./middleware/cors";
import type { Bindings } from "./types/bindings";
import {
	AuthSignUpEndpoint,
	AuthSignInEndpoint,
	AuthSignOutEndpoint,
	AuthSessionEndpoint,
} from "./endpoints/auth/openapi";
import { handleJwks } from "./routes/jwks";
import {
	GetUserSettingsEndpoint,
	UpdateUserSettingsEndpoint,
	GetOrganizationSettingsEndpoint,
	UpdateOrganizationSettingsEndpoint,
	GetResolvedSettingsEndpoint,
	GetOrganizationMembershipEndpoint,
} from "./endpoints/settings/openapi";
import {
	ListAuditLogsEndpoint,
	GetAuditLogEndpoint,
	VerifyAuditChainEndpoint,
	ExportAuditLogsEndpoint,
} from "./endpoints/audit/openapi";
// Note: Subscription management is now handled by Better Auth Stripe plugin
// Our custom routes only handle usage tracking and org limit checks
import {
	PrepareAvatarUploadEndpoint,
	UploadAvatarEndpoint,
	DeleteAvatarEndpoint,
} from "./endpoints/upload/openapi";
import {
	AdminGetStatsEndpoint,
	AdminKvFlushEndpoint,
	AdminPromoteUserEndpoint,
} from "./endpoints/admin/openapi";
import { runWithExecutionContext } from "./auth/execution-context";
import { settingsRoutes } from "./routes/settings";
import { internalSettingsRoutes } from "./routes/internal-settings";
import { auditRoutes } from "./routes/audit";
import { internalAuditRoutes } from "./routes/internal-audit";
import { subscriptionRoutes } from "./routes/subscription";
import { organizationRoutes } from "./routes/organization";
import { webhookRoutes } from "./routes/webhooks";
import { uploadRoutes } from "./routes/upload";
import { adminRoutes } from "./routes/admin";
import { adminOrganizationsRoutes } from "./routes/admin-organizations";
import { internalOrganizationsRoutes } from "./routes/internal-organizations";
import { pricingRoutes } from "./routes/pricing";
import { apiKeysRoutes } from "./routes/api-keys";
import { internalApiKeysRoutes } from "./routes/internal-api-keys";
import { usageRightsRoutes } from "./routes/usage-rights";
import { internalUsageRightsRoutes } from "./routes/internal-usage-rights";
import { licenseAdminRoutes } from "./routes/license-admin";
import { subscriptionAdminRoutes } from "./routes/subscription-admin";
import { amlSettingsProxyRoutes } from "./routes/aml-settings-proxy";
import {
	GetAmlComplianceSettingsEndpoint,
	PutAmlComplianceSettingsEndpoint,
	PatchAmlComplianceSettingsEndpoint,
	PatchAmlSelfServiceSettingsEndpoint,
} from "./endpoints/aml-settings/openapi";

// Start a Hono app
export const app = new Hono<{ Bindings: Bindings }>();

const appMeta: AppMeta = {
	name: pkg.name,
	version: pkg.version,
	description: pkg.description,
};

// Establish AsyncLocalStorage scope for every request so that all route
// handlers (auth, settings, subscription, admin, etc.) can access the
// Cloudflare ExecutionContext via getExecutionContext() / executeInBackground().
// This is required for Better Auth's backgroundTasks.handler to call
// ctx.waitUntil() on background D1 writes from any route, not just /api/auth/*.
app.use("*", async (c, next) => {
	return runWithExecutionContext(c.executionCtx, next);
});

// Global middleware - Better Auth handles its own CORS via trustedOrigins config
// Only apply CORS middleware to non-Better Auth routes
const corsMiddleware = createCorsMiddleware();
app.use("*", async (c, next) => {
	if (c.req.path.startsWith("/api/auth")) {
		return next();
	}
	return corsMiddleware(c, next);
});

app.onError((err, c) => {
	if (err instanceof ApiException) {
		// If it's a Chanfana ApiException, let Chanfana handle the response
		return c.json(
			{ success: false, errors: err.buildResponse() },
			err.status as ContentfulStatusCode,
		);
	}

	console.error("Global error handler caught:", err); // Log the error if it's not known

	Sentry.captureException(err, {
		tags: { context: "global-error-handler" },
	});

	// For other errors, return a generic 500 response
	return c.json(
		{
			success: false,
			errors: [{ code: 7000, message: "Internal Server Error" }],
		},
		500,
	);
});

// Setup OpenAPI registry
const openapi = fromHono(app, {
	// Keep the autogenerated docs available; serve Scalar at `/docsz`.
	docs_url: "/docs",
	schema: {
		info: getOpenApiInfo(appMeta),
	},
});

app.get("/", (c) => {
	if (c.req.header("x-force-error") === "1") {
		throw new Error("Forced error");
	}

	return c.json({ name: appMeta.name, version: appMeta.version });
});

app.get("/healthz", (c) => {
	return c.json({ ok: true });
});

app.get("/docsz", (c) => {
	return c.html(getScalarHtml(appMeta));
});

// Register dedicated JWKS handler BEFORE Better Auth routes.
// This bypasses Better Auth's full pipeline (rate limiting KV ops, Prisma D1 query)
// for the JWKS endpoint, making it immune to intermittent D1 slowdowns.
// See src/routes/jwks.ts for details.
app.get("/api/auth/jwks", handleJwks);

// Register Better Auth routes (actual implementation - handles requests)
// Must be registered BEFORE OpenAPI documentation routes so they handle requests first
registerBetterAuthRoutes(app);

// Register Better Auth OpenAPI documentation (for API docs generation only)
// These routes are registered after Better Auth routes, so they won't intercept requests
openapi.post("/api/auth/sign-up", AuthSignUpEndpoint);
openapi.post("/api/auth/sign-in", AuthSignInEndpoint);
openapi.post("/api/auth/sign-out", AuthSignOutEndpoint);
openapi.get("/api/auth/session", AuthSessionEndpoint);

// Register Settings routes (actual implementation)
app.route("/api/settings", settingsRoutes);

// Register AML Compliance Settings proxy (proxied to aml-svc via service binding)
app.route("/api/settings/aml-compliance", amlSettingsProxyRoutes);

// Register Internal routes for service bindings
app.route("/internal/settings", internalSettingsRoutes);

// Admin organizations (session + admin role; admin app calls this directly)
app.route("/admin/organizations", adminOrganizationsRoutes);

// Internal organizations (service binding access, no auth; for org member enumeration)
app.route("/internal/organizations", internalOrganizationsRoutes);

// Register Settings OpenAPI documentation
openapi.get("/api/settings/user", GetUserSettingsEndpoint);
openapi.patch("/api/settings/user", UpdateUserSettingsEndpoint);
openapi.get(
	"/api/settings/organization/:orgId",
	GetOrganizationSettingsEndpoint,
);
openapi.patch(
	"/api/settings/organization/:orgId",
	UpdateOrganizationSettingsEndpoint,
);
openapi.get(
	"/api/settings/organization/:orgId/membership",
	GetOrganizationMembershipEndpoint,
);
openapi.get("/api/settings/resolved", GetResolvedSettingsEndpoint);

// Register AML Compliance Settings OpenAPI documentation
openapi.get(
	"/api/settings/aml-compliance/:orgId",
	GetAmlComplianceSettingsEndpoint,
);
openapi.put(
	"/api/settings/aml-compliance/:orgId",
	PutAmlComplianceSettingsEndpoint,
);
openapi.patch(
	"/api/settings/aml-compliance/:orgId",
	PatchAmlComplianceSettingsEndpoint,
);
openapi.patch(
	"/api/settings/aml-compliance/:orgId/self-service",
	PatchAmlSelfServiceSettingsEndpoint,
);

// Register Audit routes (actual implementation)
app.route("/api/audit", auditRoutes);

// Register Internal Audit routes for service bindings
app.route("/internal/audit", internalAuditRoutes);

// Register Audit OpenAPI documentation
openapi.get("/api/audit", ListAuditLogsEndpoint);
openapi.get("/api/audit/verify", VerifyAuditChainEndpoint);
openapi.get("/api/audit/:id", GetAuditLogEndpoint);
openapi.post("/api/audit/export", ExportAuditLogsEndpoint);

// Register Subscription routes (usage tracking and org limits)
// Note: Checkout, cancel, upgrade are handled by Better Auth at /api/auth/subscription/*
app.route("/api/subscription", subscriptionRoutes);

// Register Pricing routes (database-driven plans, prices, and limits)
app.route("/api/pricing", pricingRoutes);

// Register API Keys routes (organization-scoped keys for third-party access)
app.route("/api/api-keys", apiKeysRoutes);

// Register Internal API Keys routes (service binding validation)
app.route("/internal/api-keys", internalApiKeysRoutes);

// Register Usage Rights routes (entitlement checks, metering, gates)
app.route("/api/usage-rights", usageRightsRoutes);

// Register Internal Usage Rights routes (service binding, no auth)
app.route("/internal/usage-rights", internalUsageRightsRoutes);

// Register Organization routes (invitation lookup by ID)
app.route("/api/organization", organizationRoutes);

// Register Stripe Webhooks (card fingerprint check and usage reset)
app.route("/webhooks", webhookRoutes);

// Register Upload routes (avatar uploads via R2)
app.route("/api/upload", uploadRoutes);

// Register Upload OpenAPI documentation
openapi.post("/api/upload/avatar/prepare", PrepareAvatarUploadEndpoint);
openapi.post("/api/upload/avatar", UploadAvatarEndpoint);
openapi.delete("/api/upload/avatar/:key", DeleteAvatarEndpoint);

// Register Admin routes (KV management, etc.)
app.route("/api/admin", adminRoutes);

// Register License Admin routes (CRUD for enterprise licenses)
app.route("/api/admin/licenses", licenseAdminRoutes);

// Register Subscription Admin routes (list, stats, usage for admin)
app.route("/api/admin/subscriptions", subscriptionAdminRoutes);

// Register Admin OpenAPI documentation
openapi.get("/api/admin/stats", AdminGetStatsEndpoint);
openapi.delete("/api/admin/kv/flush", AdminKvFlushEndpoint);
openapi.post("/api/admin/users/:userId/promote", AdminPromoteUserEndpoint);

// Register other endpoints
openapi.post("/dummy/:slug", DummyEndpoint);
