// Polyfill for node:async_hooks (required for better-auth in Cloudflare Workers)
import "./polyfills/async_hooks";

import { ApiException, fromHono } from "chanfana";
import { Hono } from "hono";
import { ContentfulStatusCode } from "hono/utils/http-status";
import { DummyEndpoint } from "./endpoints/dummyEndpoint";
import pkg from "../package.json";
import { getOpenApiInfo, getScalarHtml, type AppMeta } from "./app-meta";
import { registerBetterAuthRoutes } from "./auth/routes";
import { createCorsMiddleware } from "./middleware/cors";
import type { Bindings } from "./types/bindings";
import {
	AuthSignUpEndpoint,
	AuthSignInEndpoint,
	AuthSignOutEndpoint,
	AuthSessionEndpoint,
	AuthJwksEndpoint,
	AuthForgotPasswordEndpoint,
	AuthResetPasswordEndpoint,
} from "./endpoints/auth/openapi";

// Start a Hono app
const app = new Hono<{ Bindings: Bindings }>();

const appMeta: AppMeta = {
	name: pkg.name,
	version: pkg.version,
	description: pkg.description,
};

// Global middleware
app.use("*", createCorsMiddleware());

app.onError((err, c) => {
	if (err instanceof ApiException) {
		// If it's a Chanfana ApiException, let Chanfana handle the response
		return c.json(
			{ success: false, errors: err.buildResponse() },
			err.status as ContentfulStatusCode,
		);
	}

	console.error("Global error handler caught:", err); // Log the error if it's not known

	// For other errors, return a generic 500 response
	return c.json(
		{
			success: false,
			errors: [{ code: 7000, message: "Internal Server Error" }],
		},
		500,
	);
});

// Setup OpenAPI registry
const openapi = fromHono(app, {
	// Keep the autogenerated docs available; serve Scalar at `/docsz`.
	docs_url: "/docs",
	schema: {
		info: getOpenApiInfo(appMeta),
	},
});

app.get("/", (c) => {
	if (c.req.header("x-force-error") === "1") {
		throw new Error("Forced error");
	}

	return c.json({ name: appMeta.name, version: appMeta.version });
});

app.get("/healthz", (c) => {
	return c.json({ ok: true });
});

app.get("/docsz", (c) => {
	return c.html(getScalarHtml(appMeta));
});

// Register Better Auth OpenAPI documentation (must be before actual routes)
openapi.post("/api/auth/sign-up", AuthSignUpEndpoint);
openapi.post("/api/auth/sign-in", AuthSignInEndpoint);
openapi.post("/api/auth/sign-out", AuthSignOutEndpoint);
openapi.get("/api/auth/session", AuthSessionEndpoint);
openapi.get("/api/auth/jwks", AuthJwksEndpoint);
openapi.post("/api/auth/forgot-password", AuthForgotPasswordEndpoint);
openapi.post("/api/auth/reset-password", AuthResetPasswordEndpoint);

// Register Better Auth routes (actual implementation - handles requests)
registerBetterAuthRoutes(app);

// Register other endpoints
openapi.post("/dummy/:slug", DummyEndpoint);

// Export the Hono app
export default app;
